#
# Copyright 2008 Department of Mathematical Sciences, New Mexico State University
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
# DEPARTMENT OF MATHEMATICAL SCIENCES OR NEW MEXICO STATE UNIVERSITY BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
# CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#

RM = rm
CP = cp
MKINSTALLDIRS = ./mkinstalldirs
CC = gcc
CFLAGS = -Wall -pedantic -g -O2

DEFINES = -DHAVE_FREETYPE -DHAVE_HBF -DHAVE_XLIB -DG_DISABLE_DEPRECATED \
	-DGDK_DISABLE_DEPRECATED -DGDK_PIXBUF_DISABLE_DEPRECATED \
	-DGTK_DISABLE_DEPRECATED -DGTK_DISABLE_SINGLE_INCLUDES -DGSEAL_ENABLE

SRCS = bdf.c \
       bdfcons.c \
       bdffnt.c \
       bdfgname.c \
       bdfgrab.c \
       bdfgrid.c \
       bdfotf.c \
       bdfpkgf.c \
       bdfpsf.c \
       fontgrid.c \
       gbdfed.c \
       gectrl.c \
       glyphedit.c \
       glyphtest.c \
       grayswatch.c \
       guiedit.c \
       guifile.c \
       guigedit.c \
       guihelp.c \
       guiops.c \
       guipref.c \
       guiutil.c \
       hbf.c \
       labcon.c

OBJS = $(SRCS:%.c=%.o)

INCS = -I. `pkg-config gtk+-2.0 --cflags freetype2 --cflags x11 --cflags`
LIBS = `pkg-config gtk+-2.0 --libs freetype2 x11`

all: gbdfed

gbdfed: $(OBJS)
	$(CC) $(STATIC) $(LDFLAGS) -o gbdfed $(OBJS) $(LIBS)

%.test: %.test.o %.o bdf.o bdfcons.o bdffnt.o bdfgname.o bdfgrab.o bdfgrid.o bdfotf.o bdfpkgf.o bdfpsf.o hbf.o
	$(CC) $(STATIC) $(CFLAGS) $^ -o $@ $(LIBS)

clean:
	$(RM) -f *.o *BAK *CKP *~ core

realclean: clean
	$(RM) -f gbdfed

distclean: clean
	$(RM) -rf gbdfed config.* Makefile autom4te.cache

.c.o:
	$(CC) $(DEFINES) $(CFLAGS) $(INCS) -c $< -o $@

deps:
	gcc -I. -MM $(SRCS) > deps

#
# Dependencies.
#
bdf.o: bdf.c bdfP.h bdf.h
bdfcons.o: bdfcons.c bdfP.h bdf.h
bdffnt.o: bdffnt.c bdfP.h bdf.h
bdfgname.o: bdfgname.c bdfP.h bdf.h
bdfgrab.o: bdfgrab.c bdfP.h bdf.h
bdfgrid.o: bdfgrid.c bdfP.h bdf.h
bdfotf.o: bdfotf.c
bdfpkgf.o: bdfpkgf.c bdfP.h bdf.h
bdfpsf.o: bdfpsf.c bdfP.h bdf.h
fontgrid.o: fontgrid.c fontgrid.h bdfP.h bdf.h
gbdfed.o: gbdfed.c gbdfed.h bdf.h fontgrid.h bdfP.h glyphtest.h labcon.h
gectrl.o: gectrl.c gectrl.h bdfP.h bdf.h gectrlbmaps.h
glyphedit.o: glyphedit.c glyphedit.h bdfP.h bdf.h
glyphtest.o: glyphtest.c glyphtest.h bdfP.h bdf.h
grayswatch.o: grayswatch.c grayswatch.h
guiedit.o: guiedit.c gbdfed.h bdf.h fontgrid.h bdfP.h glyphtest.h labcon.h
guifile.o: guifile.c gbdfed.h bdf.h fontgrid.h bdfP.h glyphtest.h labcon.h
guigedit.o: guigedit.c gbdfed.h bdf.h fontgrid.h bdfP.h glyphtest.h \
glyphedit.h labcon.h gectrl.h
guihelp.o: guihelp.c gbdfed.h bdf.h fontgrid.h bdfP.h glyphtest.h htext.h
guiops.o: guiops.c gbdfed.h bdf.h fontgrid.h bdfP.h glyphtest.h
guipref.o: guipref.c gbdfed.h bdf.h fontgrid.h bdfP.h glyphtest.h
guiutil.o: guiutil.c gbdfed.h bdf.h fontgrid.h bdfP.h glyphtest.h
hbf.o: hbf.c hbf.h
labcon.o: labcon.c labcon.h

# end of Makefile
